### This is simply the steps taken to remove the original Dataset of 8.2GB and over 600 million data points to a useful state

In [53]:
!pip install geopandas folium matplotlib

import sys
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import geopandas as gpd
from IPython.display import HTML

path = './Data'

Requirement already satisfied: geopandas in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (1.0.1)
Requirement already satisfied: folium in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (0.19.4)
Requirement already satisfied: matplotlib in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: numpy>=1.22 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (0.10.0)
Requirement already satisfied: packaging in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=1.4.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.3.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (3.7.0)
Requirement already satisfied: shapely>=2.0.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from geopandas) (2.0.7)
Requirement already satisfied: branca>=0.6.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from folium) (3.1.5)
Requirement already satisfied: requests in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from folium) (2025.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: pillow>=8 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: pytz>=2020.1 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from pandas>=1.4.0->geopandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from pandas>=1.4.0->geopandas) (2025.1)
Requirement already satisfied: certifi in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from pyogrio>=0.7.2->geopandas) (2024.12.14)
Requirement already satisfied: six>=1.5 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from requests->folium) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/Adam/.pyenv/versions/venv/lib/python3.13/site-packages (from requests->folium) (2.3.0)

## CSV

In [54]:
df = pd.read_csv(f'{path}/building_permits/building_permits.csv')

In [55]:
def size_of_df(df):
    print("Current size of dataframe:")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print(f"Total data points: {df.size}")
# Method 2: As a list
column_list = list(df.columns)

# Method 4: To get a list of column names as strings
column_names = df.columns.tolist()

display(df.head())

# Method 1: Using display() with styling
from IPython.display import display
display(df.columns.to_frame(name='Column Names'))

# Method 1: Convert index to frame
display(df.index.to_frame(name='Row Names'))



# # Method 2: Using pandas styling
# print("With Styling:")
# print(pd.DataFrame(df.columns, columns=['Column Names']).to_string())

# Method 3: Using a prettier format with line breaks
print("With Line Breaks:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

# Method 4: As a formatted table
print("As a Formatted Table:")
display(pd.DataFrame({
    'Column Names': df.columns,
    'Data Type': df.dtypes
}))

size_of_df(df)

,REF_DATE,GEO,DGUID,Type of building,Type of work,Variables,"Seasonal adjustment, value type",UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2021A000011124,Total residential and non-residential,"Types of work, total",Value of permits,"Unadjusted, current",Dollars,81,thousands,3,v1578839311,1.1.1.1.1,5332663.0,NaN,NaN,NaN,0
1,2017-01,Canada,2021A000011124,Total residential and non-residential,"Types of work, total",Value of permits,"Seasonally adjusted, current",Dollars,81,thousands,3,v1578843489,1.1.1.1.2,7493913.0,NaN,NaN,NaN,0
2,2017-01,Canada,2021A000011124,Total residential and non-residential,"Types of work, total",Value of permits,"Unadjusted, constant dollars",Dollars,81,thousands,3,v1578917521,1.1.1.1.3,5074786.0,NaN,NaN,NaN,0
3,2017-01,Canada,2021A000011124,Total residential and non-residential,"Types of work, total",Value of permits,"Seasonally adjusted, constant dollars",Dollars,81,thousands,3,v1578921699,1.1.1.1.4,7159871.0,NaN,NaN,NaN,0
4,2017-01,Canada,2021A000011124,Total residential and non-residential,"Types of work, total",Number of dwelling-units created,"Unadjusted, constant dollars",Number,223,units,0,v1578944299,1.1.1.2.3,NaN,..,NaN,NaN,0

                                                    Column Names
REF_DATE                                                REF_DATE
GEO                                                          GEO
DGUID                                                      DGUID
Type of building                                Type of building
Type of work                                        Type of work
Variables                                              Variables
Seasonal adjustment, value type  Seasonal adjustment, value type
UOM                                                          UOM
UOM_ID                                                    UOM_ID
SCALAR_FACTOR                                      SCALAR_FACTOR
SCALAR_ID                                              SCALAR_ID
VECTOR                                                    VECTOR
COORDINATE                                            COORDINATE
VALUE                                                      VALUE
STATUS                                                    STATUS
SYMBOL                                                    SYMBOL
TERMINATED                                            TERMINATED
DECIMALS                                                DECIMALS

          Row Names
0                 0
1                 1
2                 2
3                 3
4                 4
...             ...
33842635   33842635
33842636   33842636
33842637   33842637
33842638   33842638
33842639   33842639

[33842640 rows x 1 columns]

With Line Breaks:
1. REF_DATE
2. GEO
3. DGUID
4. Type of building
5. Type of work
6. Variables
7. Seasonal adjustment, value type
8. UOM
9. UOM_ID
10. SCALAR_FACTOR
11. SCALAR_ID
12. VECTOR
13. COORDINATE
14. VALUE
15. STATUS
16. SYMBOL
17. TERMINATED
18. DECIMALS
As a Formatted Table:

                                                    Column Names Data Type
REF_DATE                                                REF_DATE    object
GEO                                                          GEO    object
DGUID                                                      DGUID    object
Type of building                                Type of building    object
Type of work                                        Type of work    object
Variables                                              Variables    object
Seasonal adjustment, value type  Seasonal adjustment, value type    object
UOM                                                          UOM    object
UOM_ID                                                    UOM_ID     int64
SCALAR_FACTOR                                      SCALAR_FACTOR    object
SCALAR_ID                                              SCALAR_ID     int64
VECTOR                                                    VECTOR    object
COORDINATE                                            COORDINATE    object
VALUE                                                      VALUE   float64
STATUS                                                    STATUS    object
SYMBOL                                                    SYMBOL   float64
TERMINATED                                            TERMINATED   float64
DECIMALS                                                DECIMALS     int64

Current size of dataframe:
Rows: 33842640
Columns: 18
Total data points: 609167520

In [56]:
# Create separate series of unique values
unique_values = {
    'Type of building': list(df['Type of building'].unique()),
    'Type of work': list(df['Type of work'].unique()),
    'Variables': list(df['Variables'].unique()),
    'Seasonal adjustment': list(df['Seasonal adjustment, value type'].unique())
}

# Find the maximum length
max_len = max(len(v) for v in unique_values.values())

# Pad shorter lists with None to make them equal length
for key in unique_values:
    unique_values[key].extend([None] * (max_len - len(unique_values[key])))

# Create and display the DataFrame
unique_df = pd.DataFrame(unique_values)
display(unique_df)

# Alternative: Display non-padded values
for col in unique_values:
    print(f"\n{col}:")
    for val in unique_values[col]:
        if val is not None:  # Only print non-None values
            print(f"- {val}")

size_of_df(df)

,Type of building,Type of work,Variables,Seasonal adjustment
0,Total residential and non-residential,"Types of work, total",Value of permits,"Unadjusted, current"
1,Total major permits residential and non-reside...,New dwelling units total,Number of dwelling-units created,"Seasonally adjusted, current"
2,Total minor residential and non-residential,New residential and non-residential constructi...,Number of dwelling-units lost,"Unadjusted, constant dollars"
3,Total residential,New construction,Number of permits,"Seasonally adjusted, constant dollars"
4,Total major residential project,Foundation,Number of dwelling-units demolished,None
...,...,...,...,...
84,"Welfare, home",None,None,None
85,"Churches, religion",None,None,None
86,Government buildings,None,None,None
87,Government legislative and administration buil...,None,None,None
88,"Other government building - police station, pr...",None,None,None

Type of building:
- Total residential and non-residential
- Total major permits residential and non-residential
- Total minor residential and non-residential
- Total residential
- Total major residential project
- Total minor residential project
- Single dwelling building total
- Major single dwelling  projects
- Minor single dwelling projects
- Single total
- Single
- Single condominium
- Mobile home
- Cottage
- Multiple dwelling building total
- Major multiple dwelling projects
- Minor multiple dwelling projects
- Double total
- Double
- Double condominium
- Row total
- Row
- Row condominium
- Apartment total
- Apartment
- Apartment condominium
- Total demolitions
- Demolition single - detached
- Demolition cottage
- Demolition semi-detached
- Demolition row
- Demolition apartment
- Total non-residential
- Total major non-residential projects
- Total minor non-residential projects
- Total industrial
- Total major industrial projects
- Total minor industrial projects
- Factories, plants
- Maintenance building
- Plant for manufacturing, processing and assembling goods
- Transportation, utilities
- Communication building
- Transportation terminal
- Utility building
- Mining and agriculture
- Mining building
- Agriculture
- Total commercial
- Total major commercial projects
- Total minor commercial projects
- Trade and services
- Motor vehicle show room (new and used) - car dealership, used car, motorcycle and tractor sale
- Retail and wholesale outlets
- Retail complex - plaza, mall, shopping center, store and office building
- Special building use - funeral director, crematorium, mausoleum
- Warehouses
- Service stations
- Office buildings
- Office building - consultant's office, doctor's office, insurance company, bank, taxi stand, office with cafeteria, office with smoke shop
- Office complex, office and store, office and apartment
- Recreation
- Theatre and performing art center - movie theatre, concert hall, opera house, cultural center
- Indoor recreational building - sports complex, tennis court and squash, community center, arena, curling club, swimming pool
- Outdoor recreational building - country club, golf club campground facilities, outdoor skating rink, outdoor swimming pool
- Hotels, restaurants
- Convention center, exhibition building
- Hotel, hotel and motel, motor hotel
- Motel, cabin for tourism
- Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory
- Restaurant, bar, tavern, night club, diner, donut shop
- Laboratories
- Total institutional and governmental
- Total major institutional and governmental projects
- Total minor institutional and governmental projects
- Schools, education
- Elementary school, kindergarten
- Secondary school, high school, junior high school
- Post-secondary institution - technical institute, trade school
- University
- Library, museum, art gallery, aquarium, botanical garden, archive building, scientific center
- Medical, hospital
- Hospital general - military, specialized
- Clinic - health unit, out-patient clinic, first aid station
- Welfare, home
- Churches, religion
- Government buildings
- Government legislative and administration building other than office building - city hall, court of justice, embassy, parliament and senate building
- Other government building - police station, prison, fire station, military building

Type of work:
- Types of work, total
- New dwelling units total
- New residential and non-residential constructions, total
- New construction
- Foundation
- Superstructure or part of a new building
- Mechanical
- Installation of a pre-fabricated building
- Additional value to previous permit(s)
- Improvements total
- Addition to existing building (structural extension) for non-residential only
- Alterations and improvements
- Garage and carport for residential construction, only
- Conversions total
- Conversion from single to multiple dwelling
- Conversion from multiple to multiple dwelling
- Conversion from non-residential to residential building
- Deconversion total
- Deconversion from single to non-residential building
- Deconversion from multiple to multiple or single dwelling or non-residential building
- Inground swimming pools for residential construction, only
- Demolitions for residential dwellings

Variables:
- Value of permits
- Number of dwelling-units created
- Number of dwelling-units lost
- Number of permits
- Number of dwelling-units demolished

Seasonal adjustment:
- Unadjusted, current
- Seasonally adjusted, current
- Unadjusted, constant dollars
- Seasonally adjusted, constant dollars
Current size of dataframe:
Rows: 33842640
Columns: 18
Total data points: 609167520

In [57]:
# Define the values to drop
values_to_drop = [
    'Inground swimming pools for residential construction, only',
    'Garage and carport for residential construction, only',
    'Foundation'
]


df_filtered = df[~df['Type of work'].isin(values_to_drop)]



# Verify the drop
print(f"Remaining unique values in 'Type of work':")
display(df_filtered['Type of work'].unique())

size_of_df(df_filtered)

Remaining unique values in 'Type of work':

array(['Types of work, total', 'New dwelling units total',
       'New residential and non-residential constructions, total',
       'New construction', 'Superstructure or part of a new building',
       'Mechanical', 'Installation of a pre-fabricated building',
       'Additional value to previous permit(s)', 'Improvements total',
       'Addition to existing building (structural extension) for non-residential only',
       'Alterations and improvements', 'Conversions total',
       'Conversion from single to multiple dwelling',
       'Conversion from multiple to multiple dwelling',
       'Conversion from non-residential to residential building',
       'Deconversion total',
       'Deconversion from single to non-residential building',
       'Deconversion from multiple to multiple or single dwelling or non-residential building',
       'Demolitions for residential dwellings'], dtype=object)

Current size of dataframe:
Rows: 30825120
Columns: 18
Total data points: 554852160

In [58]:
def size_of_df(df):
    print("Current size of dataframe:")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print(f"Total data points: {df.size}")

# Show all unique values in Type of building
print("All unique values in Type of building:")
display(df_filtered['Type of building'].unique())

# Check if values match exactly
for value in more_values_to_drop:
    if value in df_filtered['Type of building'].values:
        print(f"Found: {value}")
    else:
        print(f"Not found: {value}")


# Create mask with case-insensitive comparison
mask = ~df_filtered['Type of building'].str.lower().isin([x.lower() for x in more_values_to_drop])
df_2 = df_filtered[mask]

size_of_df(df_2)


print("Unique values in Type of building:")
for val in sorted(df_filtered['Type of building'].unique()):
    print(f"'{val}'")

All unique values in Type of building:

array(['Total residential and non-residential',
       'Total major permits residential and non-residential',
       'Total minor residential and non-residential', 'Total residential',
       'Total major residential project',
       'Total minor residential project',
       'Single dwelling building total',
       'Major single dwelling  projects',
       'Minor single dwelling projects', 'Single total', 'Single',
       'Single condominium', 'Mobile home', 'Cottage',
       'Multiple dwelling building total',
       'Major multiple dwelling projects',
       'Minor multiple dwelling projects', 'Double total', 'Double',
       'Double condominium', 'Row total', 'Row', 'Row condominium',
       'Apartment total', 'Apartment', 'Apartment condominium',
       'Total demolitions', 'Demolition single - detached',
       'Demolition cottage', 'Demolition semi-detached', 'Demolition row',
       'Demolition apartment', 'Total non-residential',
       'Total major non-residential projects',
       'Total minor non-residential projects', 'Total industrial',
       'Total major industrial projects',
       'Total minor industrial projects', 'Factories, plants',
       'Maintenance building',
       'Plant for manufacturing, processing and assembling goods',
       'Transportation, utilities', 'Communication building',
       'Transportation terminal', 'Utility building',
       'Mining and agriculture', 'Mining building', 'Agriculture',
       'Total commercial', 'Total major commercial projects',
       'Total minor commercial projects', 'Trade and services',
       'Motor vehicle show room (new and used) - car dealership, used car, motorcycle and tractor sale',
       'Retail and wholesale outlets',
       'Retail complex - plaza, mall, shopping center, store and office building',
       'Special building use - funeral director, crematorium, mausoleum',
       'Warehouses', 'Service stations', 'Office buildings',
       "Office building - consultant's office, doctor's office, insurance company, bank, taxi stand, office with cafeteria, office with smoke shop",
       'Office complex, office and store, office and apartment',
       'Recreation',
       'Theatre and performing art center - movie theatre, concert hall, opera house, cultural center',
       'Indoor recreational building - sports complex, tennis court and squash, community center, arena, curling club, swimming pool',
       'Outdoor recreational building - country club, golf club campground facilities, outdoor skating rink, outdoor swimming pool',
       'Hotels, restaurants', 'Convention center, exhibition building',
       'Hotel, hotel and motel, motor hotel', 'Motel, cabin for tourism',
       "Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory",
       'Restaurant, bar, tavern, night club, diner, donut shop',
       'Laboratories', 'Total institutional and governmental',
       'Total major institutional and governmental projects',
       'Total minor institutional and governmental projects',
       'Schools, education', 'Elementary school, kindergarten',
       'Secondary school, high school, junior high school',
       'Post-secondary institution - technical institute, trade school',
       'University',
       'Library, museum, art gallery, aquarium, botanical garden, archive building, scientific center',
       'Medical, hospital', 'Hospital general - military, specialized',
       'Clinic - health unit, out-patient clinic, first aid station',
       'Welfare, home', 'Churches, religion', 'Government buildings',
       'Government legislative and administration building other than office building - city hall, court of justice, embassy, parliament and senate building',
       'Other government building - police station, prison, fire station, military building'],
      dtype=object)

Found: Total non-residential
Found: Total major non-residential projects
Found: Total minor non-residential projects
Found: Total industrial
Found: Total major industrial projects
Found: Total minor industrial projects
Found: Factories, plants
Found: Maintenance building
Found: Plant for manufacturing, processing and assembling goods
Found: Transportation, utilities
Found: Communication building
Found: Transportation terminal
Found: Utility building
Found: Mining and agriculture
Found: Mining building
Found: Agriculture
Found: Total commercial
Found: Total major commercial projects
Found: Total minor commercial projects
Found: Trade and services
Found: Motor vehicle show room (new and used) - car dealership, used car, motorcycle and tractor sale
Found: Retail and wholesale outlets
Found: Retail complex - plaza, mall, shopping center, store and office building
Found: Special building use - funeral director, crematorium, mausoleum
Found: Warehouses
Found: Service stations
Found: Office buildings
Found: Office building - consultant's office, doctor's office, insurance company, bank, taxi stand, office with cafeteria, office with smoke shop
Found: Office complex, office and store, office and apartment
Found: Recreation
Found: Theatre and performing art center - movie theatre, concert hall, opera house, cultural center
Found: Indoor recreational building - sports complex, tennis court and squash, community center, arena, curling club, swimming pool
Found: Outdoor recreational building - country club, golf club campground facilities, outdoor skating rink, outdoor swimming pool
Found: Hotels, restaurants
Found: Convention center, exhibition building
Found: Hotel, hotel and motel, motor hotel
Found: Motel, cabin for tourism
Found: Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory
Found: Restaurant, bar, tavern, night club, diner, donut shop
Found: Laboratories
Found: Total institutional and governmental
Found: Total major institutional and governmental projects
Found: Total minor institutional and governmental projects
Found: Schools, education
Found: Elementary school, kindergarten
Found: Secondary school, high school, junior high school
Found: Post-secondary institution - technical institute, trade school
Found: University
Found: Library, museum, art gallery, aquarium, botanical garden, archive building, scientific center
Found: Medical, hospital
Found: Hospital general - military, specialized
Found: Clinic - health unit, out-patient clinic, first aid station
Found: Welfare, home
Found: Churches, religion
Found: Government buildings
Found: Government legislative and administration building other than office building - city hall, court of justice, embassy, parliament and senate building
Found: Other government building - police station, prison, fire station, military building
Current size of dataframe:
Rows: 11407632
Columns: 18
Total data points: 205337376
Unique values in Type of building:
'Agriculture'
'Apartment'
'Apartment condominium'
'Apartment total'
'Churches, religion'
'Clinic - health unit, out-patient clinic, first aid station'
'Communication building'
'Convention center, exhibition building'
'Cottage'
'Demolition apartment'
'Demolition cottage'
'Demolition row'
'Demolition semi-detached'
'Demolition single - detached'
'Double'
'Double condominium'
'Double total'
'Elementary school, kindergarten'
'Factories, plants'
'Government buildings'
'Government legislative and administration building other than office building - city hall, court of justice, embassy, parliament and senate building'
'Hospital general - military, specialized'
'Hotel, hotel and motel, motor hotel'
'Hotels, restaurants'
'Indoor recreational building - sports complex, tennis court and squash, community center, arena, curling club, swimming pool'
'Laboratories'
'Library, museum, art gallery, aquarium, botanical garden, archive building, scientific center'
'Maintenance building'
'Major multiple dwelling projects'
'Major single dwelling  projects'
'Medical, hospital'
'Mining and agriculture'
'Mining building'
'Minor multiple dwelling projects'
'Minor single dwelling projects'
'Mobile home'
'Motel, cabin for tourism'
'Motor vehicle show room (new and used) - car dealership, used car, motorcycle and tractor sale'
'Multiple dwelling building total'
'Office building - consultant's office, doctor's office, insurance company, bank, taxi stand, office with cafeteria, office with smoke shop'
'Office buildings'
'Office complex, office and store, office and apartment'
'Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory'
'Other government building - police station, prison, fire station, military building'
'Outdoor recreational building - country club, golf club campground facilities, outdoor skating rink, outdoor swimming pool'
'Plant for manufacturing, processing and assembling goods'
'Post-secondary institution - technical institute, trade school'
'Recreation'
'Restaurant, bar, tavern, night club, diner, donut shop'
'Retail and wholesale outlets'
'Retail complex - plaza, mall, shopping center, store and office building'
'Row'
'Row condominium'
'Row total'
'Schools, education'
'Secondary school, high school, junior high school'
'Service stations'
'Single'
'Single condominium'
'Single dwelling building total'
'Single total'
'Special building use - funeral director, crematorium, mausoleum'
'Theatre and performing art center - movie theatre, concert hall, opera house, cultural center'
'Total commercial'
'Total demolitions'
'Total industrial'
'Total institutional and governmental'
'Total major commercial projects'
'Total major industrial projects'
'Total major institutional and governmental projects'
'Total major non-residential projects'
'Total major permits residential and non-residential'
'Total major residential project'
'Total minor commercial projects'
'Total minor industrial projects'
'Total minor institutional and governmental projects'
'Total minor non-residential projects'
'Total minor residential and non-residential'
'Total minor residential project'
'Total non-residential'
'Total residential'
'Total residential and non-residential'
'Trade and services'
'Transportation terminal'
'Transportation, utilities'
'University'
'Utility building'
'Warehouses'
'Welfare, home'

In [59]:
# First check current size
def size_of_df(df):
    print("Current size of dataframe:")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    print(f"Total data points: {df.size}")

# Create mask for residential-only values
residential_mask = ~df_filtered['Type of building'].isin([
    'Total non-residential',
    'Total major non-residential projects',
    'Total minor non-residential projects',
    'Total industrial',
    'Total major industrial projects',
    'Total minor industrial projects',
    'Factories, plants',
    'Maintenance building',
    'Plant for manufacturing, processing and assembling goods',
    'Transportation, utilities',
    'Communication building',
    'Transportation terminal',
    'Utility building',
    'Mining and agriculture',
    'Mining building',
    'Agriculture',
    'Total commercial',
    'Total major commercial projects',
    'Total minor commercial projects',
    'Trade and services',
    'Motor vehicle show room (new and used) - car dealership, used car, motorcycle and tractor sale',
    'Retail and wholesale outlets',
    'Retail complex - plaza, mall, shopping center, store and office building',
    'Special building use - funeral director, crematorium, mausoleum',
    'Warehouses',
    'Service stations',
    'Office buildings',
    'Office building - consultant\'s office, doctor\'s office, insurance company, bank, taxi stand, office with cafeteria, office with smoke shop',
    'Office complex, office and store, office and apartment',
    'Recreation',
    'Theatre and performing art center - movie theatre, concert hall, opera house, cultural center',
    'Indoor recreational building - sports complex, tennis court and squash, community center, arena, curling club, swimming pool',
    'Outdoor recreational building - country club, golf club campground facilities, outdoor skating rink, outdoor swimming pool',
    'Hotels, restaurants',
    'Convention center, exhibition building',
    'Hotel, hotel and motel, motor hotel',
    'Motel, cabin for tourism',
    'Restaurant, bar, tavern, night club, diner, donut shop',
    'Laboratories',
    'Total institutional and governmental',
    'Total major institutional and governmental projects',
    'Total minor institutional and governmental projects',
    'Schools, education',
    'Elementary school, kindergarten',
    'Secondary school, high school, junior high school',
    'Post-secondary institution - technical institute, trade school',
    'University',
    'Library, museum, art gallery, aquarium, botanical garden, archive building, scientific center',
    'Medical, hospital',
    'Hospital general - military, specialized',
    'Clinic - health unit, out-patient clinic, first aid station',
    'Welfare, home',
    'Churches, religion',
    'Government buildings',
    'Government legislative and administration building other than office building - city hall, court of justice, embassy, parliament and senate building',
    'Other government building - police station, prison, fire station, military building'
])

# Apply the mask
df_filtered_2 = df_filtered[residential_mask]

# Verify the drop worked
print("\nBefore filtering:")
size_of_df(df_filtered)
print("\nAfter filtering:")
size_of_df(df_filtered_2)

# Show remaining building types
print("\nRemaining building types:")
display(df_filtered_2['Type of building'].unique())

size_of_df(df_filtered_2)

Before filtering:
Current size of dataframe:
Rows: 30825120
Columns: 18
Total data points: 554852160

After filtering:
Current size of dataframe:
Rows: 11764032
Columns: 18
Total data points: 211752576

Remaining building types:

array(['Total residential and non-residential',
       'Total major permits residential and non-residential',
       'Total minor residential and non-residential', 'Total residential',
       'Total major residential project',
       'Total minor residential project',
       'Single dwelling building total',
       'Major single dwelling  projects',
       'Minor single dwelling projects', 'Single total', 'Single',
       'Single condominium', 'Mobile home', 'Cottage',
       'Multiple dwelling building total',
       'Major multiple dwelling projects',
       'Minor multiple dwelling projects', 'Double total', 'Double',
       'Double condominium', 'Row total', 'Row', 'Row condominium',
       'Apartment total', 'Apartment', 'Apartment condominium',
       'Total demolitions', 'Demolition single - detached',
       'Demolition cottage', 'Demolition semi-detached', 'Demolition row',
       'Demolition apartment',
       "Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory"],
      dtype=object)

Current size of dataframe:
Rows: 11764032
Columns: 18
Total data points: 211752576

In [60]:
# Remove the additional accommodation type
df_filtered_2 = df_filtered_2[df_filtered_2['Type of building'] != "Other accommodation - student's residence, boarding house, religious residence, hostel, dormitory"]

# Verify the drop
print("After removing 'Other accommodation':")
display(df_filtered_2['Type of building'].unique())

# Show updated DataFrame size
size_of_df(df_filtered_2)

After removing 'Other accommodation':

array(['Total residential and non-residential',
       'Total major permits residential and non-residential',
       'Total minor residential and non-residential', 'Total residential',
       'Total major residential project',
       'Total minor residential project',
       'Single dwelling building total',
       'Major single dwelling  projects',
       'Minor single dwelling projects', 'Single total', 'Single',
       'Single condominium', 'Mobile home', 'Cottage',
       'Multiple dwelling building total',
       'Major multiple dwelling projects',
       'Minor multiple dwelling projects', 'Double total', 'Double',
       'Double condominium', 'Row total', 'Row', 'Row condominium',
       'Apartment total', 'Apartment', 'Apartment condominium',
       'Total demolitions', 'Demolition single - detached',
       'Demolition cottage', 'Demolition semi-detached', 'Demolition row',
       'Demolition apartment'], dtype=object)

Current size of dataframe:
Rows: 11407632
Columns: 18
Total data points: 205337376

In [61]:
df_filtered_2 = df_filtered_2.drop(columns=['UOM_ID', 'SCALAR_ID', 'STATUS',	'SYMBOL', 'TERMINATED', 'DECIMALS'])

size_of_df(df_filtered_2)

Current size of dataframe:
Rows: 11407632
Columns: 12
Total data points: 136891584

In [62]:
print(df_filtered_2.columns.to_frame)
df_filtered_2 = df_filtered_2.drop(columns=['VECTOR','COORDINATE'])

<bound method Index.to_frame of Index(['REF_DATE', 'GEO', 'DGUID', 'Type of building', 'Type of work',
       'Variables', 'Seasonal adjustment, value type', 'UOM', 'SCALAR_FACTOR',
       'VECTOR', 'COORDINATE', 'VALUE'],
      dtype='object')>

In [63]:
size_of_df(df_filtered_2)
print(df_filtered_2.columns.to_frame)

Current size of dataframe:
Rows: 11407632
Columns: 10
Total data points: 114076320
<bound method Index.to_frame of Index(['REF_DATE', 'GEO', 'DGUID', 'Type of building', 'Type of work',
       'Variables', 'Seasonal adjustment, value type', 'UOM', 'SCALAR_FACTOR',
       'VALUE'],
      dtype='object')>

In [64]:
df_filtered_2.to_csv('./Data/building_permits/building_permits_residential.csv', index=False)